// SPDX-FileCopyrightText: 2026 ReallyMe LLC
//
// SPDX-License-Identifier: MIT OR Apache-2.0

#![allow(clippy::expect_used)]

use reallyme_openid4vp_types::RequestUriMethod;
use zeroize::Zeroize;

use crate::transport::{
    parse_authorization_request_transport, AuthorizationRequestTransport, RequestTransportPolicy,
};
use crate::WalletErrorReason;

const VALID_COMPACT_JWS: &str = "c2lnbmVk.cmVxdWVzdA.and0";
const VALID_COMPACT_JWE: &str = "eyJhbGciOiJFQ0RILUVTIn0..aXY.Y2lwaGVy.dGFn";

#[test]
fn classifies_post_request_uri_without_verifier_supplied_wallet_nonce() {
    let transport = parse_authorization_request_transport(
        "client_id=x509_san_dns%3Averifier.example&request_uri=https%3A%2F%2Fverifier.example%2Frequest.jwt&request_uri_method=post",
        RequestTransportPolicy::default(),
    )
    .expect("transport parses");

    assert_eq!(
        transport,
        AuthorizationRequestTransport::RequestUri {
            uri: "https://verifier.example/request.jwt".to_owned(),
            method: RequestUriMethod::Post,
            wallet_nonce: None,
            expected_client_id: Some("x509_san_dns:verifier.example".to_owned()),
        }
    );
}

#[test]
fn rejects_verifier_supplied_wallet_nonce_for_post_request_uri() {
    let err = parse_authorization_request_transport(
        "request_uri=https://verifier.example/request.jwt&request_uri_method=post&wallet_nonce=abc",
        RequestTransportPolicy::default(),
    )
    .expect_err("wallet_nonce is generated by the wallet request-uri POST");

    assert_eq!(err.reason(), WalletErrorReason::UnexpectedWalletNonce);
}

#[test]
fn rejects_wallet_nonce_for_get_request_uri() {
    let err = parse_authorization_request_transport(
        "request_uri=https://verifier.example/request.jwt&wallet_nonce=abc",
        RequestTransportPolicy::default(),
    )
    .expect_err("wallet_nonce is invalid for GET retrieval");

    assert_eq!(err.reason(), WalletErrorReason::UnexpectedWalletNonce);
}

#[test]
fn rejects_conflicting_request_and_request_uri() {
    let query =
        format!("request={VALID_COMPACT_JWS}&request_uri=https://verifier.example/request.jwt");
    let err = parse_authorization_request_transport(&query, RequestTransportPolicy::default())
        .expect_err("request and request_uri are mutually exclusive");

    assert_eq!(
        err.reason(),
        WalletErrorReason::ConflictingRequestObjectParameters
    );
}

#[test]
fn rejects_duplicate_authorization_request_parameters() {
    let query = format!("request={VALID_COMPACT_JWS}&request=other.header.payload");
    let err = parse_authorization_request_transport(&query, RequestTransportPolicy::default())
        .expect_err("duplicate request parameters are ambiguous");

    assert_eq!(
        err.reason(),
        WalletErrorReason::DuplicateAuthorizationRequestParameter
    );
}

#[test]
fn rejects_uppercase_request_uri_method() {
    let err = parse_authorization_request_transport(
        "request_uri=https://verifier.example/request.jwt&request_uri_method=POST&wallet_nonce=abc",
        RequestTransportPolicy::default(),
    )
    .expect_err("request_uri_method is case-sensitive");

    assert_eq!(err.reason(), WalletErrorReason::UnsupportedRequestUriMethod);
}

#[test]
fn rejects_unknown_request_uri_transport_parameter() {
    let err = parse_authorization_request_transport(
        "client_id=x509_san_dns%3Averifier.example&unsupported=value&request_uri=https://verifier.example/request.jwt",
        RequestTransportPolicy::default(),
    )
    .expect_err("unknown outer request parameters are rejected");

    assert_eq!(
        err.reason(),
        WalletErrorReason::InvalidAuthorizationRequestTransport
    );
}

#[test]
fn rejects_malformed_percent_encoding() {
    let err = parse_authorization_request_transport(
        "request_uri=https%3A%2F%2Fverifier.example%2Grequest.jwt",
        RequestTransportPolicy::default(),
    )
    .expect_err("malformed percent encoding is rejected");

    assert_eq!(
        err.reason(),
        WalletErrorReason::InvalidAuthorizationRequestTransport
    );
}

#[test]
fn rejects_oversized_request_object_by_value() {
    let policy = RequestTransportPolicy {
        max_request_jwt_bytes: 4,
        require_signed_request_object: true,
        ..RequestTransportPolicy::default()
    };

    let err = parse_authorization_request_transport("request=12345", policy)
        .expect_err("oversized request object is rejected before verification");

    assert_eq!(err.reason(), WalletErrorReason::RequestObjectTooLarge);
}

#[test]
fn classifies_signed_request_object_by_value() {
    let query = format!("client_id=x509_san_dns%3Averifier.example&request={VALID_COMPACT_JWS}");
    let transport =
        parse_authorization_request_transport(&query, RequestTransportPolicy::default())
            .expect("signed by-value request object parses");

    assert_eq!(
        transport,
        AuthorizationRequestTransport::RequestJwt {
            jwt: VALID_COMPACT_JWS.to_owned(),
            expected_client_id: Some("x509_san_dns:verifier.example".to_owned()),
            expected_wallet_nonce: None,
        }
    );
}

#[test]
fn redacts_and_zeroizes_request_transport_values() {
    let mut transport = AuthorizationRequestTransport::RequestJwt {
        jwt: VALID_COMPACT_JWS.to_owned(),
        expected_client_id: Some("sensitive-client".to_owned()),
        expected_wallet_nonce: Some("sensitive-nonce".to_owned()),
    };

    let debug = format!("{transport:?}");
    assert!(!debug.contains(VALID_COMPACT_JWS));
    assert!(!debug.contains("sensitive-client"));

    transport.zeroize();
    let AuthorizationRequestTransport::RequestJwt {
        jwt,
        expected_client_id,
        expected_wallet_nonce,
    } = &transport
    else {
        return;
    };
    assert!(jwt.is_empty());
    assert!(expected_client_id.is_none());
    assert!(expected_wallet_nonce.is_none());
}

#[test]
fn classifies_encrypted_request_object_by_value() {
    let query = format!("request={VALID_COMPACT_JWE}");
    let transport =
        parse_authorization_request_transport(&query, RequestTransportPolicy::default())
            .expect("encrypted by-value request object parses");

    assert_eq!(
        transport,
        AuthorizationRequestTransport::RequestJwt {
            jwt: VALID_COMPACT_JWE.to_owned(),
            expected_client_id: None,
            expected_wallet_nonce: None,
        }
    );
}

#[test]
fn rejects_malformed_request_object_by_value() {
    let err = parse_authorization_request_transport(
        "request=header.payload",
        RequestTransportPolicy::default(),
    )
    .expect_err("malformed Request Object is rejected before JOSE verification");

    assert_eq!(err.reason(), WalletErrorReason::InvalidRequestObject);
}

#[test]
fn rejects_inline_params_when_signed_request_required() {
    let err = parse_authorization_request_transport(
        "client_id=x509_san_dns%3Averifier.example&nonce=abc",
        RequestTransportPolicy::default(),
    )
    .expect_err("strict policy rejects inline params");

    assert_eq!(
        err.reason(),
        WalletErrorReason::InvalidAuthorizationRequestTransport
    );
}
