// SPDX-FileCopyrightText: 2026 ReallyMe LLC
//
// SPDX-License-Identifier: MIT OR Apache-2.0

use core::fmt;

use thiserror::Error;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::{RuntimeError, RuntimeErrorReason};

pub(crate) const MAX_VERIFIER_EVIDENCE_IDENTIFIER_BYTES: usize = 128;

/// OIDF module identity committed with the verifier session and Request Object.
#[derive(Clone, PartialEq, Eq)]
pub struct VerifierEvidenceContext {
    plan_id: String,
    profile_id: String,
    module_id: String,
    module_name: String,
}

impl VerifierEvidenceContext {
    /// Construct a bounded certification context from an authenticated launch request.
    pub fn new(
        plan_id: String,
        profile_id: String,
        module_id: String,
        module_name: String,
    ) -> Result<Self, RuntimeError> {
        validate_verifier_evidence_identifier(&plan_id)?;
        validate_verifier_evidence_identifier(&profile_id)?;
        validate_verifier_evidence_identifier(&module_id)?;
        validate_verifier_evidence_identifier(&module_name)?;
        Ok(Self {
            plan_id,
            profile_id,
            module_id,
            module_name,
        })
    }

    /// Return the immutable OIDF test plan id.
    pub fn plan_id(&self) -> &str {
        &self.plan_id
    }

    /// Return the immutable certification profile id.
    pub fn profile_id(&self) -> &str {
        &self.profile_id
    }

    /// Return the OIDF module instance id.
    pub fn module_id(&self) -> &str {
        &self.module_id
    }

    /// Return the OIDF module name.
    pub fn module_name(&self) -> &str {
        &self.module_name
    }
}

impl fmt::Debug for VerifierEvidenceContext {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VerifierEvidenceContext")
            .field("values", &"<redacted>")
            .finish()
    }
}

impl Zeroize for VerifierEvidenceContext {
    fn zeroize(&mut self) {
        self.plan_id.zeroize();
        self.profile_id.zeroize();
        self.module_id.zeroize();
        self.module_name.zeroize();
    }
}

impl Drop for VerifierEvidenceContext {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl ZeroizeOnDrop for VerifierEvidenceContext {}

pub(crate) fn validate_verifier_evidence_identifier(value: &str) -> Result<(), RuntimeError> {
    let bytes = value.as_bytes();
    let Some(first) = bytes.first() else {
        return Err(RuntimeError::new(RuntimeErrorReason::MissingField));
    };
    if bytes.len() > MAX_VERIFIER_EVIDENCE_IDENTIFIER_BYTES
        || !first.is_ascii_alphanumeric()
        || !bytes
            .iter()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(*byte, b'.' | b'_' | b'-'))
    {
        return Err(RuntimeError::new(RuntimeErrorReason::InvalidFormBody));
    }
    Ok(())
}

/// Verifier runtime operation observed for certification evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerifierEvidenceObservationKind {
    /// A hosted Request Object was requested by the wallet.
    RequestObjectRetrieval,
    /// A plain `direct_post` Authorization Response was processed.
    DirectPostValidation,
    /// An encrypted `direct_post.jwt` Authorization Response was processed.
    DirectPostJwtValidation,
    /// A pending HAIP result completed same-device browser follow-back.
    FollowBackRedemption,
}

/// Non-PII disposition of an observed verifier runtime operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerifierEvidenceOutcome {
    /// Runtime processing completed with a successful HTTP response.
    Accepted,
    /// Runtime processing produced a protocol or transport rejection.
    Rejected,
}

/// Typed observation supplied to a host-owned evidence recorder.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VerifierEvidenceObservation {
    /// Protocol operation that was observed.
    pub kind: VerifierEvidenceObservationKind,
    /// Whether the runtime accepted or rejected that operation.
    pub outcome: VerifierEvidenceOutcome,
    /// HTTP status generated by the real runtime path.
    pub http_status: u16,
}

impl VerifierEvidenceObservation {
    pub(crate) const fn from_disposition(
        kind: VerifierEvidenceObservationKind,
        outcome: VerifierEvidenceOutcome,
        http_status: u16,
    ) -> Self {
        Self {
            kind,
            outcome,
            http_status,
        }
    }
}

/// Stable reason returned when the host cannot durably record an observation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerifierEvidenceRecorderErrorReason {
    /// The evidence store is temporarily unavailable.
    Unavailable,
    /// The observation could not be committed durably.
    WriteFailed,
}

/// Typed host evidence-recorder error without request data or allocation.
#[derive(Debug, Error, Clone, Copy, PartialEq, Eq)]
#[error("verifier evidence recorder error: {reason:?}")]
pub struct VerifierEvidenceRecorderError {
    reason: VerifierEvidenceRecorderErrorReason,
}

impl VerifierEvidenceRecorderError {
    /// Construct an evidence-recorder error from its stable reason.
    pub const fn new(reason: VerifierEvidenceRecorderErrorReason) -> Self {
        Self { reason }
    }

    /// Return the stable, non-PII failure reason.
    pub const fn reason(self) -> VerifierEvidenceRecorderErrorReason {
        self.reason
    }
}

/// Host boundary for durable verifier certification observations.
///
/// `lookup_key` is the same private adapter key used for the session or hosted
/// Request Object. The host maps it to OIDF module context without exposing the
/// key in exported evidence. Implementations must commit before returning; an
/// error causes the runtime to fail closed with a generic internal problem.
pub trait VerifierEvidenceRecorder: Send + Sync {
    /// Durably record one observation for a private runtime lookup key.
    fn record_verifier_observation(
        &self,
        lookup_key: &str,
        observation: VerifierEvidenceObservation,
    ) -> Result<(), VerifierEvidenceRecorderError>;
}

#[cfg(test)]
#[path = "record_verifier_evidence_tests.rs"]
mod tests;
