# SPDX-FileCopyrightText: 2026 ReallyMe LLC
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "reallyme-openid4vp-http"
version = "0.1.1"
description = "Optional OpenID4VP HTTP transport adapter traits."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true
include = ["/src/**/*.rs", "/Cargo.toml", "/README.md"]

[features]
default = ["native"]
native = ["reallyme-openid4vp-wallet/native"]
wasm = ["reallyme-openid4vp-wallet/wasm"]

[dependencies]
reallyme-openid4vp-types = { path = "../types", version = "0.1.1", default-features = false }
reallyme-openid4vp-wallet = { path = "../wallet", version = "0.1.1", default-features = false }
thiserror = { workspace = true }
zeroize = { workspace = true }

[lints]
workspace = true
